.yamllint:
    extends: default

    ignore: |
        *.param.yaml

    rules:
        braces:
            level: error
            max-spaces-inside: 1 # Ensure consistent spacing inside braces
        comments:
            level: error
            min-spaces-from-content: 1 # Keep compatibility with C++ and Python
        document-start:
            level: error
            present: false # Document start markers not needed
        line-length:
            level: warning
            max: 80 # Enforce a maximum line length
        indentation:
            spaces: 4 # Set tab width to 4 spaces
            indent-sequences: whatever
        hyphens:
            max-spaces-after: 4
        truthy:
            level: error
            check-keys: false # Allow 'on' for GitHub Actions
        quoted-strings:
            level: error
            required: only-when-needed # Ensure consistent style for strings
